<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <Authors>WinGnome contributors</Authors>
    <Product>WinGnome</Product>
  </PropertyGroup>
</Project>
