using WinGnome.Core.Windows;

namespace WinGnome.Core.Tests.Windows;

public class AppPathMatchTests
{
    private const string GitHubRoot = @"C:\Users\sam\AppData\Local\GitHubDesktop";

    [Fact]
    public void IsSameInstall_SamePathDifferentCaseAndSlashes_IsTrue()
    {
        Assert.True(AppPathMatch.IsSameInstall(@"C:\Program Files\Foo\Foo.exe", "c:/program files/foo/FOO.EXE"));
    }

    [Fact]
    public void IsSameInstall_StubBesideAppVersionFolder_IsTrue()
    {
        Assert.True(AppPathMatch.IsSameInstall(GitHubRoot + @"\GitHubDesktop.exe", GitHubRoot + @"\app-3.6.6\GitHubDesktop.exe"));
    }

    [Fact]
    public void IsSameInstall_UpdateExeBesideAppVersionFolder_IsTrue()
    {
        Assert.True(AppPathMatch.IsSameInstall(
            @"C:\Users\sam\AppData\Local\Discord\Update.exe",
            @"C:\Users\sam\AppData\Local\Discord\app-1.0.9\Discord.exe"));
    }

    [Fact]
    public void IsSameInstall_AppVersionFolderUnderDifferentRoot_IsFalse()
    {
        Assert.False(AppPathMatch.IsSameInstall(GitHubRoot + @"\GitHubDesktop.exe", @"C:\Users\sam\AppData\Local\Other\app-3.6.6\GitHubDesktop.exe"));
    }

    [Fact]
    public void IsSameInstall_AppFolderThatIsNotAVersion_IsFalse()
    {
        Assert.False(AppPathMatch.IsSameInstall(GitHubRoot + @"\GitHubDesktop.exe", GitHubRoot + @"\app-foo\GitHubDesktop.exe"));
    }

    [Fact]
    public void IsSameInstall_DifferentFolder_IsFalse()
    {
        Assert.False(AppPathMatch.IsSameInstall(@"C:\Program Files\Foo\Foo.exe", @"C:\Program Files\Bar\Foo.exe"));
    }

    [Fact]
    public void IsSameInstall_ProcessInASubfolderThatIsNotSquirrel_IsFalse()
    {
        Assert.False(AppPathMatch.IsSameInstall(@"C:\Program Files\Foo\Foo.exe", @"C:\Program Files\Foo\bin\Foo.exe"));
    }

    [Theory]
    [InlineData(null, @"C:\Foo\Foo.exe")]
    [InlineData("", @"C:\Foo\Foo.exe")]
    [InlineData("   ", @"C:\Foo\Foo.exe")]
    [InlineData(@"C:\Foo\Foo.exe", null)]
    [InlineData(@"C:\Foo\Foo.exe", "")]
    [InlineData(null, null)]
    [InlineData("", "")]
    public void IsSameInstall_MissingPath_IsFalse(string? target, string? process)
    {
        Assert.False(AppPathMatch.IsSameInstall(target, process));
    }

    [Theory]
    [InlineData(@"C:\Root\app-1\X.exe", @"C:\Root")]
    [InlineData(@"C:\Root\app-3.6.6\X.exe", @"C:\Root")]
    [InlineData(@"C:\Root\APP-1.0.0-beta.2\X.exe", @"C:\Root")]
    [InlineData("C:/Root/app-1.2/X.exe", @"C:\Root")]
    public void SquirrelRoot_AppVersionFolder_ReturnsItsParent(string processPath, string expected)
    {
        Assert.Equal(expected, AppPathMatch.SquirrelRoot(processPath));
    }

    [Theory]
    [InlineData(@"C:\Root\app-\X.exe")]
    [InlineData(@"C:\Root\app-foo\X.exe")]
    [InlineData(@"C:\Root\app-1.x\X.exe")]
    [InlineData(@"C:\Root\application-1.0\X.exe")]
    [InlineData(@"C:\Root\X.exe")]
    [InlineData(@"app-1.0\X.exe")]
    [InlineData("X.exe")]
    [InlineData("")]
    [InlineData(null)]
    public void SquirrelRoot_NotASquirrelLayout_IsNull(string? processPath)
    {
        Assert.Null(AppPathMatch.SquirrelRoot(processPath));
    }

    [Theory]
    [InlineData("Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}", true)]
    [InlineData("microsoft.autogenerated.{923DD477-5846-686B-A659-0FCCD73851A8}", true)]
    [InlineData("  Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}", true)]
    [InlineData("Microsoft.VisualStudioCode", false)]
    [InlineData("com.squirrel.GitHubDesktop.GitHubDesktop", false)]
    [InlineData("", false)]
    [InlineData(null, false)]
    public void IsGeneratedAumid_RecognisesShellGeneratedIds(string? id, bool expected)
    {
        Assert.Equal(expected, AppPathMatch.IsGeneratedAumid(id));
    }
}
