using System.Text.RegularExpressions;
using WinGnome.Core.Shell;

namespace WinGnome.Core.Windows;

/// <summary>
/// Decides whether a running process belongs to the install a shortcut points at, for apps whose windows carry no
/// AppUserModelID that matches their shortcut (Electron sets it process-wide, where other processes can't read it).
/// </summary>
public static partial class AppPathMatch
{
    private const string GeneratedAumidPrefix = "Microsoft.AutoGenerated.";

    /// <summary>
    /// True when <paramref name="processPath"/> is <paramref name="targetPath"/> (ignoring case and slash direction),
    /// when the process runs from a Squirrel "app-&lt;version&gt;" folder whose parent is the target's folder, or when
    /// the process is a same-file-named executable in a direct child folder of the target's folder.
    /// Squirrel installs put a stub (<c>&lt;root&gt;\Name.exe</c>) or <c>&lt;root&gt;\Update.exe</c> behind the
    /// shortcut and run the real executable from <c>&lt;root&gt;\app-1.2.3\</c>; launcher-stub installs (Docker
    /// Desktop) put a root launcher behind the shortcut and run the UI from <c>&lt;root&gt;\frontend\Name.exe</c>
    /// with no AUMID another process can read (KI-100).
    /// </summary>
    public static bool IsSameInstall(string? targetPath, string? processPath)
    {
        if (string.IsNullOrWhiteSpace(targetPath) || string.IsNullOrWhiteSpace(processPath))
        {
            return false;
        }

        var target = PathText.Canonical(targetPath);
        var process = PathText.Canonical(processPath);
        if (target == process)
        {
            return true;
        }

        var root = SquirrelRoot(processPath);
        if (root is not null && string.Equals(PathText.Canonical(root), PathText.DirectoryName(target), StringComparison.Ordinal))
        {
            return true;
        }

        return IsLauncherChild(target, process);
    }

    /// <summary>
    /// True when the process is a same-file-named executable in a direct child folder of the target's folder, both
    /// already canonical; <c>C:\frontend\X.exe</c> pairs with <c>C:\X.exe</c>, never the other way round — the
    /// reverse layout needs no rule, because a pin to a launcher in a subfolder is a path pin whose UI-at-the-root
    /// window already matches by identity or by the exe-name fallback. The guard rejects a drive root ("c:") and a
    /// folder-less relative path as the shared folder; a UNC share root (<c>\\server\share</c>) is not guarded and
    /// does pair with its child folders (KI-100: shortcut targets are almost always local).
    /// </summary>
    private static bool IsLauncherChild(string target, string process) =>
        string.Equals(PathText.FileName(target), PathText.FileName(process), StringComparison.Ordinal)
        && PathText.DirectoryName(PathText.DirectoryName(target)).Length > 0
        && string.Equals(
            PathText.DirectoryName(target),
            PathText.DirectoryName(PathText.DirectoryName(process)),
            StringComparison.Ordinal);

    /// <summary>
    /// The install root of a process that runs from a Squirrel "app-&lt;version&gt;" folder (the folder above it,
    /// with backslash separators), or null when the process is not laid out that way.
    /// </summary>
    public static string? SquirrelRoot(string? processPath)
    {
        if (string.IsNullOrWhiteSpace(processPath))
        {
            return null;
        }

        var folder = PathText.DirectoryName(processPath.Trim().Replace('/', '\\'));
        if (!SquirrelAppFolder().IsMatch(PathText.FileName(folder)))
        {
            return null;
        }

        var root = PathText.DirectoryName(folder);
        return root.Length == 0 ? null : root;
    }

    /// <summary>
    /// True for the AppUserModelIDs the shell generates for shortcuts without one ("Microsoft.AutoGenerated.{…}").
    /// Those shortcuts are launchers with arguments (WSL GUI apps, developer prompts, folder shortcuts), so their
    /// target executable never stands for "the app".
    /// </summary>
    public static bool IsGeneratedAumid(string? id) =>
        !string.IsNullOrWhiteSpace(id) && id.TrimStart().StartsWith(GeneratedAumidPrefix, StringComparison.OrdinalIgnoreCase);

    [GeneratedRegex(@"^app-[0-9]+(\.[0-9]+)*(-[\w.]+)?$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex SquirrelAppFolder();
}
