using System.Text.RegularExpressions;
using WinGnome.Core.Shell;

namespace WinGnome.Core.Windows;

/// <summary>
/// Decides whether a running process belongs to the install a shortcut points at, for apps whose windows carry no
/// AppUserModelID that matches their shortcut (Electron sets it process-wide, where other processes can't read it).
/// </summary>
public static partial class AppPathMatch
{
    private const string GeneratedAumidPrefix = "Microsoft.AutoGenerated.";

    /// <summary>
    /// True when <paramref name="processPath"/> is <paramref name="targetPath"/> (ignoring case and slash direction),
    /// or when the process runs from a Squirrel "app-&lt;version&gt;" folder whose parent is the target's folder.
    /// Squirrel installs put a stub (<c>&lt;root&gt;\Name.exe</c>) or <c>&lt;root&gt;\Update.exe</c> behind the
    /// shortcut and run the real executable from <c>&lt;root&gt;\app-1.2.3\</c>.
    /// </summary>
    public static bool IsSameInstall(string? targetPath, string? processPath)
    {
        if (string.IsNullOrWhiteSpace(targetPath) || string.IsNullOrWhiteSpace(processPath))
        {
            return false;
        }

        var target = PathText.Canonical(targetPath);
        if (target == PathText.Canonical(processPath))
        {
            return true;
        }

        var root = SquirrelRoot(processPath);
        return root is not null && string.Equals(PathText.Canonical(root), PathText.DirectoryName(target), StringComparison.Ordinal);
    }

    /// <summary>
    /// The install root of a process that runs from a Squirrel "app-&lt;version&gt;" folder (the folder above it,
    /// with backslash separators), or null when the process is not laid out that way.
    /// </summary>
    public static string? SquirrelRoot(string? processPath)
    {
        if (string.IsNullOrWhiteSpace(processPath))
        {
            return null;
        }

        var folder = PathText.DirectoryName(processPath.Trim().Replace('/', '\\'));
        if (!SquirrelAppFolder().IsMatch(PathText.FileName(folder)))
        {
            return null;
        }

        var root = PathText.DirectoryName(folder);
        return root.Length == 0 ? null : root;
    }

    /// <summary>
    /// True for the AppUserModelIDs the shell generates for shortcuts without one ("Microsoft.AutoGenerated.{…}").
    /// Those shortcuts are launchers with arguments (WSL GUI apps, developer prompts, folder shortcuts), so their
    /// target executable never stands for "the app".
    /// </summary>
    public static bool IsGeneratedAumid(string? id) =>
        !string.IsNullOrWhiteSpace(id) && id.TrimStart().StartsWith(GeneratedAumidPrefix, StringComparison.OrdinalIgnoreCase);

    [GeneratedRegex(@"^app-[0-9]+(\.[0-9]+)*(-[\w.]+)?$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex SquirrelAppFolder();
}
