using WinGnome.Core.Settings;
using WinGnome.Core.Shell;

namespace WinGnome.Core.Tests.Shell;

public class LaunchPlannerTests
{
    private const string Desktop = "Microsoft.WindowsTerminal";
    private const string Packaged = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";

    public enum PinState { None, Normal, AlwaysElevated }

    private static PinnedApp? Pin(string launchId, PinState state) => state switch
    {
        PinState.None => null,
        _ => new PinnedApp { Name = "App", LaunchId = launchId, RunAsAdministrator = state == PinState.AlwaysElevated },
    };

    [Theory]
    [InlineData(LaunchModifiers.None, PinState.None, false)]
    [InlineData(LaunchModifiers.None, PinState.Normal, false)]
    [InlineData(LaunchModifiers.None, PinState.AlwaysElevated, true)]
    [InlineData(LaunchModifiers.Control, PinState.None, false)]
    [InlineData(LaunchModifiers.Control, PinState.Normal, false)]
    [InlineData(LaunchModifiers.Control, PinState.AlwaysElevated, true)]
    [InlineData(LaunchModifiers.Shift, PinState.None, false)]
    [InlineData(LaunchModifiers.Shift, PinState.Normal, false)]
    [InlineData(LaunchModifiers.Shift, PinState.AlwaysElevated, true)]
    [InlineData(LaunchModifiers.Control | LaunchModifiers.Shift, PinState.None, true)]
    [InlineData(LaunchModifiers.Control | LaunchModifiers.Shift, PinState.Normal, true)]
    [InlineData(LaunchModifiers.Control | LaunchModifiers.Shift, PinState.AlwaysElevated, true)]
    public void Plan_DesktopApp_ElevatesOnCtrlShiftOrAlwaysPin(LaunchModifiers modifiers, PinState pin, bool elevate)
    {
        var request = LaunchPlanner.Plan(Desktop, modifiers, Pin(Desktop, pin));

        Assert.Equal(new LaunchRequest(Desktop, null, elevate), request);
    }

    [Theory]
    [InlineData(LaunchModifiers.None, PinState.None)]
    [InlineData(LaunchModifiers.None, PinState.Normal)]
    [InlineData(LaunchModifiers.None, PinState.AlwaysElevated)]
    [InlineData(LaunchModifiers.Control, PinState.AlwaysElevated)]
    [InlineData(LaunchModifiers.Shift, PinState.AlwaysElevated)]
    [InlineData(LaunchModifiers.Control | LaunchModifiers.Shift, PinState.None)]
    [InlineData(LaunchModifiers.Control | LaunchModifiers.Shift, PinState.Normal)]
    [InlineData(LaunchModifiers.Control | LaunchModifiers.Shift, PinState.AlwaysElevated)]
    public void Plan_PackagedApp_NeverElevates(LaunchModifiers modifiers, PinState pin)
    {
        var request = LaunchPlanner.Plan(Packaged, modifiers, Pin(Packaged, pin));

        Assert.Equal(new LaunchRequest(Packaged, null, false), request);
    }

    [Fact]
    public void Plan_CtrlShiftWithAlt_StillElevates()
    {
        var request = LaunchPlanner.Plan(Desktop, LaunchModifiers.Control | LaunchModifiers.Shift | LaunchModifiers.Alt, null);

        Assert.True(request.Elevate);
    }

    [Fact]
    public void Plan_Pin_SuppliesItsArguments()
    {
        var pin = new PinnedApp { Name = "Calc", LaunchId = @"C:\Tools\calc.exe", Arguments = "/x" };

        var request = LaunchPlanner.Plan(@"C:\Tools\calc.exe", LaunchModifiers.None, pin);

        Assert.Equal(new LaunchRequest(@"C:\Tools\calc.exe", "/x", false), request);
    }

    [Fact]
    public void Plan_TrimsTheLaunchId()
    {
        var request = LaunchPlanner.Plan("  " + Desktop + " ", LaunchModifiers.None, null);

        Assert.Equal(Desktop, request.LaunchId);
    }

    [Fact]
    public void PlanElevated_DesktopApp_Elevates()
    {
        var pin = new PinnedApp { Name = "Tool", LaunchId = @"C:\Tools\tool.exe", Arguments = "--dev" };

        Assert.Equal(new LaunchRequest(@"C:\Tools\tool.exe", "--dev", true), LaunchPlanner.PlanElevated(@"C:\Tools\tool.exe", pin));
    }

    [Fact]
    public void PlanElevated_PackagedApp_DoesNotElevate()
    {
        Assert.Equal(new LaunchRequest(Packaged, null, false), LaunchPlanner.PlanElevated(Packaged, null));
    }

    [Theory]
    [InlineData(@"C:\Windows\System32\cmd.exe", LaunchTargetKind.File)]
    [InlineData(@"C:\Users\me\Desktop\Tool.lnk", LaunchTargetKind.File)]
    [InlineData(@"\\server\share\tool.exe", LaunchTargetKind.File)]
    [InlineData(@"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Mozilla Firefox\firefox.exe", LaunchTargetKind.File)]
    [InlineData("ms-settings:", LaunchTargetKind.Uri)]
    [InlineData("shell:RecycleBinFolder", LaunchTargetKind.Uri)]
    [InlineData("https://example.com/", LaunchTargetKind.Uri)]
    [InlineData(Packaged, LaunchTargetKind.PackagedApp)]
    [InlineData(Desktop, LaunchTargetKind.DesktopApp)]
    [InlineData("Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}", LaunchTargetKind.DesktopApp)]
    public void Classify_RecognisesEachKindOfLaunchId(string launchId, LaunchTargetKind expected)
    {
        Assert.Equal(expected, LaunchPlanner.Classify(launchId));
    }

    [Theory]
    [InlineData(@"C:\Windows\System32\cmd.exe", true)]
    [InlineData(@"C:\Users\me\Desktop\Tool.LNK", true)]
    [InlineData(@"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Mozilla Firefox\firefox.exe", true)]
    [InlineData(@"C:\Users\me\notes.txt", false)]
    [InlineData(@"C:\Tools", false)]
    [InlineData("ms-settings:", false)]
    [InlineData("shell:RecycleBinFolder", false)]
    [InlineData(Packaged, false)]
    [InlineData(Desktop, true)]
    [InlineData("", false)]
    [InlineData("   ", false)]
    public void CanElevate_OnlyDesktopAppsAndExecutables(string launchId, bool expected)
    {
        Assert.Equal(expected, LaunchPlanner.CanElevate(launchId));
    }
}
